ENT.Type 			= "anim"
ENT.PrintName		= ""
ENT.Author			= "Ultra"
ENT.m_intUseRange 	= 128
ENT.m_tblPresets 	= {
{ Name = "Fireplace Loop", ID = "RDfjXj5EGqI" },
{ Name = "Ceiling Fan Trick Knockdown", ID = "eVXKKaWJTls" },
{ Name = "Leafblower Volcano", ID = "K8FwMlkoxjI" },
{ Name = "LEAVE IMMEDIATELY", ID = "hxwyWCOtoqE" },
{ Name = "Art 1992", ID = "oRIyw-pJkUk" },
{ Name = "JonTron - Cassette tape original", ID = "B_sDqk_SUhE" },
{ Name = "Cat Alarm", ID = "VInFTkglc_s" },
{ Name = "Don't Hug Me I'm Scared 4", ID = "G9FGgwCQ22w" },
{ Name = "Furze's Invention show - JETWIPE", ID = "ntvBa6u9ldY" },
{ Name = "Nyan Cat", ID = "O7j802RKtDc" },
{ Name = "OneDeag - Apply Directly to the Forehead", ID = "sMD6QbBGxhc" },
{ Name = "God Dammit George Bush...", ID = "RaivuFH5TAY" },
{ Name = "Unicorn - Samurai", ID = "UO2zrCExdrU" },
{ Name = "Duck.exe has stopped working", ID = "SwxdBiazu8M" },
{ Name = "Shia LaBeouf TED Talk", ID = "os6U77Hhm_s" },
{ Name = "Daler Mehndi - Tunak Tunak Tun Video", ID = "vTIIMJ9tUc8" },
{ Name = "Half life: Full Life Consequences", ID = "OHxyZaZlaOs" },
{ Name = "Half-Life: Full-life Consequences 2", ID = "h8yHguvYYyQ" },
{ Name = "Half-Life Full-life Consequences: Free Man", ID = "ULWgEnnmcv4" },
{ Name = "[Vinesauce] Bad Half-Life Mods", ID = "wBHh7i40fDc" },
{ Name = "[Vinesauce] Shitty Sonic Fangames", ID = "XvYSQAify4U" },
{ Name = "[Vinesauce] G-Mod RP", ID = "blb7DejmklY" },
{ Name = "[Vinesauce] Shitty Super Mario World ROM Hacks", ID = "414lmf7flw4" },
{ Name = "ERB 1-1: John Lennon V Bill O'Reilly", ID = "YHRxv-40WMU" },
{ Name = "ERB 1-2: Darth Vader vs Hitler", ID = "AFA-rOls8YA" },
{ Name = "ERB 1-3: Abe Lincoln VS Chuck Norris", ID = "zj2Zf9tlg2Y" },
{ Name = "ERB 1-4: Sarah Palin VS Lady Gaga", ID = "mhTd4_Ids80" },
{ Name = "ERB 1-5: Hulk Hogan VS Kim Jong-il", ID = "7rE0-ek6MZA" },
{ Name = "ERB 1-6: Justin Bieber vs Beethoven", ID = "UcTLJ692F70" },
{ Name = "ERB 1-7: Einstein vs Stephen Hawking", ID = "zn7-fVtT16k" },
{ Name = "ERB 1-8: Genghis Khan vs Easter Bunny", ID = "WA4tLCGcTG4" },
{ Name = "ERB 1-9: Napoleon vs Napoleon", ID = "AeNYDwbm9qw" },
{ Name = "ERB 1-10: Billy Mays vs Ben Franklin", ID = "TAaE7sJahiw" },
{ Name = "ERB 1-11: Gandalf vs Dumbledore", ID = "ZIMoQHpvFQQ" },
{ Name = "ERB 1-12: Dr Seuss VS Shakespeare", ID = "l3w2MTXBebg" },
{ Name = "ERB 1-13: Mr T vs Mr Rogers", ID = "7ZsKqbt3gQ0" },
{ Name = "ERB 1-14: Columbus vs Captain Kirk", ID = "xBzoBgfm55w" },
{ Name = "ERB 1-15: Nice Peter vs EpicLLOYD", ID = "IVJVCoHDAXs" },
{ Name = "ERB 2-1: Hitler vs Vader 2", ID = "CeLrlmV9A" },
{ Name = "ERB 2-2: Master Chief vs Leonidas", ID = "mgVwv0ZuPhM" },
{ Name = "ERB 2-3: Mario Bros vs Wright Bros", ID = "1_hKLfTKU5Y" },
{ Name = "ERB 2-4: Michael Jackson VS Elvis Presley", ID = "0M0RbaPxq2k" },
{ Name = "ERB 2-5: Cleopatra VS Marilyn Monroe", ID = "vICX-6dMOuA" },
{ Name = "ERB 2-6: Steve Jobs vs Bill Gates", ID = "njos57IJf-0" },
{ Name = "ERB 2-7: Frank Sinatra vs Freddie Mercury", ID = "K5a_v0MP_Fk" },
{ Name = "ERB 2-8: Barack Obama vs Mitt Romney", ID = "dX_1B0w7Hzc" },
{ Name = "ERB 2-9: Doc Brown vs Doctor Who", ID = "xDj7gvc_dsA" },
{ Name = "ERB 2-10: Bruce Lee vs Clint Eastwood", ID = "eHCyaJS4Cbs" },
{ Name = "ERB 2-11: Batman vs Sherlock Holmes", ID = "17CLlZuiBkQ" },
{ Name = "ERB 2-12: Moses vs Santa Claus", ID = "0kRAKXFrYQ4" },
{ Name = "ERB 2-13: Adam vs Eve", ID = "liLU2tEz7KY" },
{ Name = "ERB 2-14: Gandhi vs Martin Luther King Jr.", ID = "-6G6CZT7h4k" },
{ Name = "ERB 2-15: Nikola Tesla vs Thomas Edison", ID = "gJ1Mz7kGVf0" },
{ Name = "ERB 2-16: Babe Ruth vs Lance Armstrong", ID = "YtO-6Xg3g2M" },
{ Name = "ERB 2-17: Mozart vs Skrillex", ID = "_6Au0xCg3PI" },
{ Name = "ERB 2-18: Rasputin vs Stalin", ID = "ZT2z0nrsQ8o" },
}